# Generated by Django 2.1.1 on 2020-02-21 02:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200220_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
